#!/usr/bin/bash

function login {
    local exit_status=1
    local http_status=$(
        curl 'http://localhost:3000/rest/user/login' \
        -H 'Content-Type: application/json' \
        -s -o /dev/null -w '%{HTTP_CODE}' \
        --data-raw '{"email": "'"$1"'", "password": "'"$2"'"}'
    )
    if [[ "$http_status" -eq 200 ]]; then
        exit_status=0
    fi
    return $exit_status
}

export -f login

SECONDS=0

parallel -j 8 --halt now,success=1 login ::: "$1" ::: $(cat "$2")

duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
